### ISSUE TITLE
Optimize amount of checks

### ISSUE THREAD

**Issue by oguzeroglu** [bpmn-io/path-intersection#14]
There might be a way to optimize the amount of iterations in findBezierIntersections method which takes the most execution time while finding intersections.

In [this line](https://github.com/bpmn-io/path-intersection/blob/030f552258fdccc57bacb743e7515a8052512ee5/intersect.js#L323) and [this line](https://github.com/bpmn-io/path-intersection/blob/030f552258fdccc57bacb743e7515a8052512ee5/intersect.js#L328) we can check if the points are inside both the first and the second bounding boxes before pushing them to arrays. In the end we'd have less points to perform segment-intersection-check.

However if this approach is to be implemented, we need to push the time values rather than points to prevent array out of bounds bugs.

Might be a good slack time topic :)

**Comment by nikku** [comment]
Isn't this already done [here](https://github.com/bpmn-io/path-intersection/blob/030f552258fdccc57bacb743e7515a8052512ee5/intersect.js#L308)?

**Comment by oguzeroglu** [comment]
No, this is to check if bounding boxes of each bezier curves intersect. My proposal is that once we create segments out of curves, it could potentially make sense to do intersection tests between these segments only if they are inside the intersection area of two bounding boxes. Therefore we could have less nested-for-loop iterations for intersection tests.

For instance, lets consider BoundingBox1 and BoundingBox2 intersect however a segment seg1 could be inside BoundingBox1 but not inside BoundingBox2, therefore it could make sense not to include such segment in intersection tests. 

I spent some time today on this solution and this kinda works, however there was a bug in bounding boxes having width or height = 0 (lines without slope). Will work more on a proper solution some other time.

**Comment by nikku** [comment]
Usually issues like "optimize this and that" are never going to be picked up, unless, as you mention someone picks these up and starts contributing.

Because of that, let's close this issue and see if future optimizations fly in via a PR :wink:.
