### ISSUE TITLE
Values with scientific notation are not parsed correctly

### ISSUE THREAD

**Issue by or** [bpmn-io/path-intersection#18]
__Describe the Bug__

Paths that contain values such as `"1.2e-14"` are not parsed correctly, resulting in no intersections.

__Steps to Reproduce__

Intersection of `"M1.12345e-15,1.12345e-15 L100,100"` and `"M100,0 L0,100"` is not found.

__Expected Behavior__

Would expect an intersection at (50, 50).

__Environment__

- OS: macOS
- Library version: v2.2.0

**Comment by nikku** [comment]
Released `v2.2.1` with a fix.
