### ISSUE TITLE
Use improved bezier curve intersection detection algorithm

### ISSUE THREAD

**Issue by nikku** [bpmn-io/path-intersection#5]
According @barmac we use an overly complex algorithm to compute our quadratic and cubic bezier curve intersections.

We could consider incorporating the [`bezier.js` intersection logic](http://pomax.github.io/bezierjs/#intersect-curve) and see if it improves our library in terms of speed, complexity, and/or bundle size.

**Comment by barmac** [comment]
We use Beziér clipping and according to [this article](http://nishitalab.org/user/nis/cdrom/cad/CAGD90Curve.pdf) it is

> ...marginally slower than an algorithm based on implicitization (...) for curves of degree four and less...

Beziér curves in SVG path are either degree two or three.

**Comment by nikku** [comment]
Open for external contributions.

**Comment by ShaMan123** [comment]
This repo is exponentially faster than bezier.js, well done!
