### ISSUE TITLE
Simple paths that cross more than once only result in one intersection

### ISSUE THREAD

**Issue by developher-net** [bpmn-io/path-intersection#6]
__Describe the Bug__

When 2 paths cross more than once, only one intersection is reported

__Steps to Reproduce__

```
const intersection = require('path-intersection')
  const pathIntersections = intersection(
    'M10,10 h8 v-5 h-5 v3',
    'M15,14 v-7 h6'
  )

  console.log(pathIntersections)
```

<img width="123" alt="Screen Shot 2019-12-06 at 6 33 21 PM" src="https://user-images.githubusercontent.com/105728/70367673-f848dc00-1856-11ea-96ab-df8fcd4c5e35.png">

Results only have 1 intersection:
```
[
  {
    x: 15,
    y: 10,
    t1: 0.625,
    t2: 0.5714285714285714,
    segment1: 1,
    segment2: 1,
    bez1: [
      10, 10, 10, 10,
      18, 10, 18, 10
    ],
    bez2: [
      15, 14, 15, 14,
      15,  7, 15,  7
    ]
  }
]
```
__Expected Behavior__

Returned list contains multiple intersections:
* x:15, y:10
* x:18, y:-3

__Environment__

- Host (Browser/Node version), if applicable: Node 12 LTS
- OS: OSX
- Library version: 1.1.1

**Comment by barmac** [comment]
Thank you for creating this issue! I can reproduce it.
