### ISSUE TITLE
Failed to detect intersection if exactly same coordinates

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/path-intersection#7]
__Describe the Bug__

Related to https://github.com/camunda/camunda-modeler/issues/1611

The intersection algorithm fails to detect intersection when the path ends _exactly_ on the other path. 

__Steps to Reproduce__

Given this [failed test case](https://github.com/bpmn-io/path-intersection/commit/e44b90dcbe170179c7af249195d07939d923e994), it's clear there should be two intersections, but only one is detected.

![image](https://user-images.githubusercontent.com/9433996/70614756-61d83a00-1c0b-11ea-813c-5258731b2b33.png)

If the last coordinate is updated by one pixel to the right, the intersection would be detected correctly.

__Expected Behavior__

Two intersections are detected.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 78
- OS: macOS 10.15
- Library version: current `master`

**Comment by nikku** [comment]
Finally a test case to reproduce the behavior that I'm seeing sporadically in my tools. :clap:

**Comment by nikku** [comment]
Could you PR the branch with the test case? Can be a good start for an investigation / fix.

**Comment by pinussilvestrus** [comment]
sure!
